name: Flutter

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Create .env file
        run: |
          echo "GOOGLE_MAPS_API_KEY=${{ secrets.GOOGLE_MAPS_API_KEY }}" > .env
        # Add any other environment variables you need

      - name: Install dependencies
        run: |
          flutter pub get

      - name: Analyze
        run: |
          flutter analyze

      # Uncomment these steps when you're ready to run tests and build
      # - name: Test
      #   run: flutter test
      # - name: Build
      #   run: flutter build apk
      # - name: Bundle
      #   run: flutter build appbundle
